all: job1  job2  job3  job4  job5  job6  job7  job8  job9  job10 job11 job12 job13 job14 job15 job16 job17 job18 job19 job20 job21 job22 job23 job24 job25 job26 job27 job28 job29 job30 
job1  :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 1 9   21  206  178  129  220   11   74
job2  :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 2 241   99   69  115  155   93  239  232
job3  :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 3 83  198  116  133  175  105   60  226
job4  :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 4 63  141  125  136  191  217  158   54
job5  :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 5 150   30   17  240  111  230  210  215
job6  :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 6 34  160  148  224   87   72  182  117
job7  :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 7 112  181  170  223   95   10  201  174
job8  :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 8 168  156  235  122   37   97  166  149
job9  :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 9 219  100   70   62  200   27   46  238
job10 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 10 236  135   20   39  192  171   42   16
job11 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 11 167  118  152  169    7   43   22   91
job12 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 12 134   47   80  102  176  199  144  197
job13 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 13 216    6  188  139  231    5    4  196
job14 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 14 153  163  177  186  119  123   59   53
job15 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 15 2  151  101  172  162   51   89  193
job16 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 16 212  114  164   71   35   15   94  205
job17 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 17 234  103   49   64  195   32   75  161
job18 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 18 48  128  207  121  124   73   86  157
job19 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 19 131  154  104  145   28  159   18  113
job20 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 20 40   33   81  147   13   44   38  179
job21 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 21 61  110   66   98   12   41   55   76
job22 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 22 132  228   58  211  183  214   50  194
job23 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 23 173  180   29   90   19   79   78   23
job24 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 24 107  221  203  143   52  184  108   24
job25 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 25 82  189   57  130  109    3  208   65
job26 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 26 190  126  137   45  138   26  229  233
job27 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 27 202    1   96  237  142   88  222  106
job28 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 28 8  187   31  120   85   25   36  225
job29 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 29 213  227  165   84  204  146  127  140
job30 :
	nice -n19 /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/runmatlab /home/gruen/Organization05/NWGcourse05/SourceCourseMaterial/Gruen/Exercises/Programs/UEver-2.3/UEMainAnalyseWindow /home/gruen/local.scratch/ 30 92   68   77  218  209   56   14  185   67
