#!/bin/bash
export LD_LIBRARY_PATH=/neuroinf/matlab7s2/sys/os/glnx86:/neuroinf/matlab7s2/bin/glnx86:/neuroinf/matlab7s2/sys/java/jre/glnx86/jre1.5.0/lib/i386/native_threads:/neuroinf/matlab7s2/sys/java/jre/glnx86/jre1.5.0/lib/i386/client:/neuroinf/matlab7s2/sys/java/jre/glnx86/jre1.5.0/lib/i386:${LD_LIBRARY_PATH}
export XAPPLRESDIR=/neuroinf/matlab7s2/X11/app-defaults
export PATH=$PWD:$PATH
"$@"
